### ISSUE TITLE
Document how the crate can be used with WASM + Browser

### ISSUE THREAD

**Issue by caniko** [NiklasEi/bevy_asset_loader#249]
Hello, I am new to the bevy space! I am making a simple game using WASM, and I see that several others have used this crate with WASM projects.

Could you briefly explain how it works with WASM?

**Comment by NiklasEi** [comment]
You can use the plugin with WASM as on any other platform. The only thing to remember is that folder loading does not work in the browser (not with Bevy's `load_folder` and not with this plugin; see the readme).
Otherwise, follow the documentation of Bevy/and Bevy templates for a WASM setup. For example, [`bevy_game_template`](https://github.com/NiklasEi/bevy_game_template) uses `bevy_asset_loader` and can run in the browser.
